SELECT DISTINCT GUIDELINES, YEAR, TEST_METHOD, POTENCY, ORGANISM_CODE, ORGANISM_CODE_TYPE, BREAKPOINT_TYPE, [HOST], 
	SITE_OF_INFECTION, REFERENCE_TABLE, REFERENCE_SEQUENCE, WHONET_ABX_CODE, WHONET_TEST, R, I, SDD, S, ECV_ECOFF, 
	ECV_ECOFF_TENTATIVE, DATE_ENTERED, DATE_MODIFIED, COMMENTS
FROM (
	SELECT row_number() OVER (
		PARTITION BY
			b.GUIDELINES, b.YEAR, b.BREAKPOINT_TYPE, b.[HOST], o.WHONET_ORG_CODE, b.SITE_OF_INFECTION, b.WHONET_TEST
		ORDER BY (
			CASE b.ORGANISM_CODE_TYPE
			WHEN 'SEROVAR_GROUP' THEN 1
			WHEN 'WHONET_ORG_CODE' THEN 2
			WHEN 'SPECIES_GROUP' THEN 3
			WHEN 'GENUS_CODE' THEN 4
			WHEN 'GENUS_GROUP' THEN 5
			WHEN 'FAMILY_CODE' THEN 6
			WHEN 'ANAEROBE+SUBKINGDOM_CODE' THEN 7
			WHEN 'ANAEROBE' THEN 8
			ELSE 9
			END
		) ASC)  AS RowRank,
		o.WHONET_ORG_CODE, o.GENUS_CODE, o.SEROVAR_GROUP, b.*
	FROM Organisms o
		INNER JOIN Breakpoints b
			ON b.ORGANISM_CODE_TYPE <> 'ALL' AND (
				o.SEROVAR_GROUP IS NOT NULL
				AND b.ORGANISM_CODE_TYPE = 'SEROVAR_GROUP'
				AND o.SEROVAR_GROUP = b.ORGANISM_CODE
			) OR (
				b.ORGANISM_CODE_TYPE = 'WHONET_ORG_CODE'
				AND o.WHONET_ORG_CODE = b.ORGANISM_CODE
			) OR (
				o.SPECIES_GROUP IS NOT NULL
				AND b.ORGANISM_CODE_TYPE = 'SPECIES_GROUP'
				AND o.SPECIES_GROUP = b.ORGANISM_CODE
			) OR (
				o.GENUS_CODE IS NOT NULL
				AND b.ORGANISM_CODE_TYPE = 'GENUS_CODE'
				AND o.GENUS_CODE = b.ORGANISM_CODE
			) OR (
				o.GENUS_GROUP IS NOT NULL
				AND b.ORGANISM_CODE_TYPE = 'GENUS_GROUP'
				AND o.GENUS_GROUP = b.ORGANISM_CODE
			) OR (
				o.FAMILY_CODE IS NOT NULL
				AND b.ORGANISM_CODE_TYPE = 'FAMILY_CODE'
				AND o.FAMILY_CODE = b.ORGANISM_CODE
			) OR (
				o.ANAEROBE = 'X'
				AND b.ORGANISM_CODE_TYPE = 'ANAEROBE+SUBKINGDOM_CODE'
				AND ((
						o.SUBKINGDOM_CODE = '+'
						AND b.ORGANISM_CODE = 'AN+'
					) OR (
						o.SUBKINGDOM_CODE = '-'
						AND b.ORGANISM_CODE = 'AN-'
				))			
			) OR (
				o.ANAEROBE = 'X'
				AND b.ORGANISM_CODE_TYPE = 'ANAEROBE'
				AND b.ORGANISM_CODE = 'ANA'
			)
	WHERE b.GUIDELINES IN ('CLSI', 'EUCAST')
		AND b.YEAR IN ('2025', '2026')
		-- Drug bug combinations. Note that these check the organism hierarchy level we want to target. (Not the bp org code).
		-- This allows us to cover a breakpoint that targets a species within the genus we specify even though the breakpoint doesn't reference the genus.
		AND (
				((o.SEROVAR_GROUP = 'ECO' OR o.GENUS_CODE = 'SAL') AND b.WHONET_ABX_CODE IN (
					'AMC', 'AMP', 'AZM', 'CTX', 'CAZ', 'CHL', 'CIP', 'COL', 'GEN', 'IMP', 'MEM', 'NAL', 'STR', 'SMX', 'TCY', 'TMP', 'SXT', 'TIO', 'CZO', 'LEX', 'FEP', 'FOX', 'CRO', 'ENR', 'TGC'))
				OR (o.GENUS_CODE = 'CAM' AND b.WHONET_ABX_CODE IN (
					'AZM', 'CIP', 'CLI', 'DOX', 'ERY', 'FLR', 'GEN', 'MEM', 'NAL', 'STR', 'TCY'))
				OR (o.GENUS_CODE = 'ENT' AND b.WHONET_ABX_CODE IN (
					'AMP', 'AVI', 'CHL', 'CIP', 'DAP', 'DOX', 'ERY', 'FOS', 'LVX', 'LNZ', 'NOR', 'PEN', 'QDA', 'TEC', 'TCY', 'VAN'))
				OR (o.GENUS_CODE = 'STA' AND b.WHONET_ABX_CODE IN (
					'AZM', 'CHL', 'CIP', 'CLR', 'DOX', 'ENR', 'ERY', 'FLR', 'GEN', 'KAN', 'LVX', 'LNZ', 'LIN', 'MAR', 'NEO', 'NOR', 'OXA', 'PEN', 'QDA', 'RIF', 'STR', 'SMX', 'TEC', 'TCY', 'TMP', 'SXT', 'VAN'))
			)
		-- Additional exclusions for CLSI ECOFFs and EUCAST Animal BPs.
		AND NOT (b.GUIDELINES = 'CLSI' AND b.BREAKPOINT_TYPE = 'ECOFF')
		AND NOT (b.GUIDELINES = 'EUCAST' AND b.BREAKPOINT_TYPE = 'Animal')	
	ORDER BY b.GUIDELINES, b.YEAR, b.BREAKPOINT_TYPE, b.[HOST], o.WHONET_ORG_CODE, b.SITE_OF_INFECTION, b.WHONET_TEST,
		 (
			CASE b.ORGANISM_CODE_TYPE
			WHEN 'SEROVAR_GROUP' THEN 1
			WHEN 'WHONET_ORG_CODE' THEN 2
			WHEN 'SPECIES_GROUP' THEN 3
			WHEN 'GENUS_CODE' THEN 4
			WHEN 'GENUS_GROUP' THEN 5
			WHEN 'FAMILY_CODE' THEN 6
			WHEN 'ANAEROBE+SUBKINGDOM_CODE' THEN 7
			WHEN 'ANAEROBE' THEN 8
			ELSE 9
			END
		) ASC
	) nested
WHERE nested.RowRank = 1